### ISSUE TITLE
[Issue]: Update CMake

### ISSUE THREAD

**Issue by hansely** [ROCm/rocAL#106]
### Problem Description

**Issue 1 - Unable to turnoff BUILD_PYPACKAGE flag** 

 https://github.com/ROCm/rocAL/blob/master/CMakeLists.txt#L53
 Users should be able to set this flag off by passing -DBUILD_PYPACKAGE=OFF. 

However, this flag does not propagate to rocal_pybind. 
https://github.com/ROCm/rocAL/blob/master/rocAL_pybind/CMakeLists.txt#L28
In the above line, BUILD_PYPACKAGE is set to ON regardless of the flag passed by the user.
Hence, there is no way to exclude rocal_pybind without manually modifying the CMakeLists.txt

**Issue 2 - No checking for cupy installation**

Cupy is required in order to use rocAL with GPU backend.
However, the current CMakeListst.txt doesn't include a checking for Cupy nor does the README file.
Therefore, the users will be notified that the Cupy is required only at runtime, which is problematic.

### Operating System

Ubuntu 20.04

### CPU

AMD Ryzen Threadripper 1900x 

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.0.0

**Comment by kiritigowda** [comment]
Resolved
